name: PR-CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"

      - name: Create Package
        uses: BigWigsMods/packager@master
        with:
          args: -d

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SavedInstances-PR${{ github.event.number }}
          path: .release/*.zip
